= Simple_Network_Documentation_Tool

Un outil web simple qui facilite et simplifie le maintien à jour de cartes logique et physique d'un réseau informatique.

== Description

Cette application web est conçue pour documenter des réseaux de petite et moyenne taille. Le projet est basé sur une pile technologique LAPP (Linux, Apache, PostgresSQL, PHP) côté serveur. Les fonctionnalités attendues sont décrites plus loin dans ce document. 

== Licences

Copyright (C) 2023 HarduinHero

Ce programme est un logiciel libre : vous pouvez le redistribuer et/ou le modifier selon les termes de la licence GNU.
et/ou le modifier selon les termes de la Licence Publique Générale GNU telle que publiée par la
la Free Software Foundation, soit la version 3 de la Licence ou toute version ultérieure.

Ce programme est distribué dans l'espoir qu'il sera utile,
mais SANS AUCUNE GARANTIE ; sans même la garantie implicite de
MERCHANTABILITÉ ou d'ADAPTATION À UN USAGE PARTICULIER.  Voir la
Licence publique générale GNU pour plus de détails.

Vous devriez avoir reçu une copie de la licence publique générale GNU
avec ce programme.  Si ce n'est pas le cas, consultez <https://www.gnu.org/licenses/>.
