= Simple_Network_Documentation_Tool
A simple web tool that makes it easy to keep a logical and physical network map up to date.

[NOTE] This document is a transcription of the original (READEME.fr.adoc) written in French.

== Description

This web application is designed to document small and medium-sized networks. The project is based on a server-side LAPP (Linux, Apache, PostgresSQL, PHP) technology stack. The expected functionality is set out later in this document. 

== Licencing

Copyright (C) 2023 HarduinHero

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
