# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QTabWidget, QToolBar,
    QVBoxLayout, QWidget)
import ui.ressources_rc

class Ui_main_window(object):
    def setupUi(self, main_window):
        if not main_window.objectName():
            main_window.setObjectName(u"main_window")
        main_window.resize(970, 664)
        main_window.setContextMenuPolicy(Qt.DefaultContextMenu)
        main_window.setWindowTitle(u"SNDT : Simple Network Documentation Tool")
        main_window.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.action_user_guide = QAction(main_window)
        self.action_user_guide.setObjectName(u"action_user_guide")
        icon = QIcon()
        icon.addFile(u":/icons/lifebuoy.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_user_guide.setIcon(icon)
        self.action_about = QAction(main_window)
        self.action_about.setObjectName(u"action_about")
        icon1 = QIcon()
        icon1.addFile(u":/icons/question.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_about.setIcon(icon1)
        self.action_new_project = QAction(main_window)
        self.action_new_project.setObjectName(u"action_new_project")
        icon2 = QIcon()
        icon2.addFile(u":/icons/briefcase--plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_project.setIcon(icon2)
        self.action_open_project = QAction(main_window)
        self.action_open_project.setObjectName(u"action_open_project")
        icon3 = QIcon()
        icon3.addFile(u":/icons/folder-horizontal-open.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_open_project.setIcon(icon3)
        self.action_settings = QAction(main_window)
        self.action_settings.setObjectName(u"action_settings")
        icon4 = QIcon()
        icon4.addFile(u":/icons/gear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_settings.setIcon(icon4)
        self.action_save = QAction(main_window)
        self.action_save.setObjectName(u"action_save")
        icon5 = QIcon()
        icon5.addFile(u":/icons/disk.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_save.setIcon(icon5)
        self.action_home = QAction(main_window)
        self.action_home.setObjectName(u"action_home")
        icon6 = QIcon()
        icon6.addFile(u":/icons/home.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_home.setIcon(icon6)
        self.action_new_object = QAction(main_window)
        self.action_new_object.setObjectName(u"action_new_object")
        icon7 = QIcon()
        icon7.addFile(u":/icons/block--plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_object.setIcon(icon7)
        self.action_new_class = QAction(main_window)
        self.action_new_class.setObjectName(u"action_new_class")
        icon8 = QIcon()
        icon8.addFile(u":/icons/blue-document-block--plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_class.setIcon(icon8)
        self.action_new_model = QAction(main_window)
        self.action_new_model.setObjectName(u"action_new_model")
        icon9 = QIcon()
        icon9.addFile(u":/icons/blueprint--plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_model.setIcon(icon9)
        self.action_new_diagram = QAction(main_window)
        self.action_new_diagram.setObjectName(u"action_new_diagram")
        icon10 = QIcon()
        icon10.addFile(u":/icons/map--plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_diagram.setIcon(icon10)
        self.central_widget = QWidget(main_window)
        self.central_widget.setObjectName(u"central_widget")
        self.verticalLayout_2 = QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tabWidget = QTabWidget(self.central_widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)

        self.verticalLayout_2.addWidget(self.tabWidget)

        main_window.setCentralWidget(self.central_widget)
        self.menubar = QMenuBar(main_window)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 970, 21))
        self.menubar.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_file.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.menu_load_example_project = QMenu(self.menu_file)
        self.menu_load_example_project.setObjectName(u"menu_load_example_project")
        icon11 = QIcon()
        icon11.addFile(u":/icons/light-bulb.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.menu_load_example_project.setIcon(icon11)
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_display = QMenu(self.menubar)
        self.menu_display.setObjectName(u"menu_display")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(main_window)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        main_window.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(main_window)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(Qt.NoToolBarArea)
        self.toolBar.setOrientation(Qt.Horizontal)
        self.toolBar.setFloatable(True)
        main_window.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu_display.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.action_new_project)
        self.menu_file.addAction(self.action_open_project)
        self.menu_file.addAction(self.menu_load_example_project.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_home)
        self.menu_file.addAction(self.action_settings)
        self.menu_help.addAction(self.action_about)
        self.menu_help.addAction(self.action_user_guide)
        self.menu_display.addSeparator()
        self.menuEdit.addAction(self.action_new_object)
        self.menuEdit.addAction(self.action_new_diagram)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.action_new_class)
        self.menuEdit.addAction(self.action_new_model)
        self.toolBar.addAction(self.action_home)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_new_object)
        self.toolBar.addAction(self.action_new_diagram)

        self.retranslateUi(main_window)

        QMetaObject.connectSlotsByName(main_window)
    # setupUi

    def retranslateUi(self, main_window):
        self.action_user_guide.setText(QCoreApplication.translate("main_window", u"User guide", None))
        self.action_about.setText(QCoreApplication.translate("main_window", u"About SNDT", None))
        self.action_new_project.setText(QCoreApplication.translate("main_window", u"New project", None))
        self.action_open_project.setText(QCoreApplication.translate("main_window", u"Open project", None))
        self.action_settings.setText(QCoreApplication.translate("main_window", u"Settings", None))
        self.action_save.setText(QCoreApplication.translate("main_window", u"Save", None))
        self.action_home.setText(QCoreApplication.translate("main_window", u"Home", None))
        self.action_new_object.setText(QCoreApplication.translate("main_window", u"New object", None))
        self.action_new_class.setText(QCoreApplication.translate("main_window", u"New class", None))
        self.action_new_model.setText(QCoreApplication.translate("main_window", u"New model", None))
        self.action_new_diagram.setText(QCoreApplication.translate("main_window", u"New diagram", None))
#if QT_CONFIG(tooltip)
        self.action_new_diagram.setToolTip(QCoreApplication.translate("main_window", u"New diagram", None))
#endif // QT_CONFIG(tooltip)
        self.menu_file.setTitle(QCoreApplication.translate("main_window", u"File", None))
        self.menu_load_example_project.setTitle(QCoreApplication.translate("main_window", u"Load example project", None))
        self.menu_help.setTitle(QCoreApplication.translate("main_window", u"Help", None))
        self.menu_display.setTitle(QCoreApplication.translate("main_window", u"Display", None))
        self.menuEdit.setTitle(QCoreApplication.translate("main_window", u"Edit", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("main_window", u"toolBar", None))
        pass
    # retranslateUi

